# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e073ce0e7ae1cff353816c32105dc75103e773b3d46e09ce51f7a23210d670ebbbfd6b58e44393376f931769812280252fba7080043c501e6229837b5c6541a

test:
  secret_key_base: c3f3bcba3a63f82b60fc66266065e4949fdd076e5b615e2271ae55df0062ea09ed7347e09411e3481c700d5fee359ffc17e6780f1667a221e4e0b40f1eb345bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
